/*
    Events
*/

drop table if exists public.events cascade;

create table public.events (
    event_id                    bigint generated by default as identity primary key,
    event_created_at            timestamp without time zone,
    event_updated_at            timestamp without time zone,
    event_address               text,
    event_begin_date            timestamp without time zone,
    event_country               text,
    event_description           text,
    event_end_date              timestamp without time zone 
        check (event_end_date is null or event_end_date >= event_begin_date),
    event_is_festival           bool not null default false,
    event_is_visible            bool not null default false,
    event_name                  text not null,
    event_poster_url            text,
    event_prices                jsonb default '[]'::jsonb,
    event_ticket_links          jsonb default '[]'::jsonb,
    event_town                  text,
    event_venue                 text,
    event_zip_code              text
);

alter table public.events owner to postgres;

create index ix_events_begin_date on public.events(event_begin_date);
create index ix_events_town on public.events(event_town);
create index ix_events_trgm on public.events using GIN (event_name gin_trgm_ops);

\i 'Events/CreateEventArtistTable.sql'
\i 'Events/CreateEventUserTable.sql'