/*
    Labels
*/

drop table if exists public.labels cascade;

create table public.labels (
   label_id                    bigint generated by default as identity primary key,
   label_created_at            timestamp without time zone,
   label_updated_at            timestamp without time zone,
   label_description           text,
   label_name                  text not null
);

alter table public.labels owner to postgres;

create index ix_labels_trgm on public.labels using GIN (label_name gin_trgm_ops);