/*
    Audit Logs
*/

drop table if exists public.audit_logs cascade;

create table public.audit_logs (
    audit_id                bigint generated by default as identity primary key,
    audit_user_id           bigint references public.users(user_id),
    audit_entity_name       varchar(50) not null,
    audit_entity_id         bigint not null,
    audit_action            varchar(20) not null,
    audit_old_data          jsonb,
    audit_new_data          jsonb,
    audit_created_at        timestamp not null default now()
);

alter table public.audit_logs owner to postgres;