/*
    Genres
*/

drop table if exists public.genres cascade;

create table public.genres (
    genre_id                    bigint generated by default as identity primary key,
    genre_created_at            timestamp without time zone,
    genre_updated_at            timestamp without time zone,
    genre_canonical_name        text not null,
    genre_color                 text not null,
    genre_confidence            numeric(3,2) default 0.80,
    genre_country_origin        text,
    genre_description           text,
    genre_era_start             date,
    genre_era_end               date,
    genre_is_visible            bool not null default false,
    genre_metadata              jsonb default '{}'::jsonb,
    genre_short_name            text,
    genre_taggable              bool not null default true,
    genre_type                  integer not null default 0
);

alter table public.genres owner to postgres;

create index ix_genres_trgm on public.genres using GIN (genre_canonical_name gin_trgm_ops);

\i 'Genres/CreateGenreAliasTable.sql'
\i 'Genres/CreateGenreRelationTable.sql'
\i 'Genres/CreateGenreClosureTable.sql'