/*
    Genres
*/

drop table if exists public.genres cascade;

create table public.genres (
   genre_id                    bigint generated by default as identity primary key,
   genre_created_at            timestamp without time zone,
   genre_updated_at            timestamp without time zone,
   genre_color                 text not null,
   genre_name                  text not null,
   genre_type                  integer not null default 0,
   genre_description           text
);

alter table public.genres owner to postgres;

create index ix_genres_trgm on public.genres using GIN (genre_name gin_trgm_ops);

\i 'Genres/CreateChildrenParentGenreTable.sql'