/*
    Genre Aliases 
*/

drop table if exists public.genre_alias cascade;

create table public.genre_alias (
    genre_alias_id                  bigint generated by default as identity primary key,
    genre_alias_genre_id            bigint not null references genres(genre_id) on delete cascade,
    genre_alias_created_at          timestamp without time zone,
    genre_alias_updated_at          timestamp without time zone,
    genre_alias_lang                text,
    genre_alias_metadata            jsonb default '{}'::jsonb,
    genre_alias_name                text not null
);

alter table public.genre_alias owner to postgres;

create index ix_genre_alias_trgm on public.genre_alias using GIN (genre_alias_name gin_trgm_ops);