/*
    Scenes / Movements
*/

drop table if exists public.scenes cascade;

create table public.scenes (
    scene_id                bigint generated by default as identity primary key,
    scene_description       text,
    scene_location          text,
    scene_metadata          jsonb default '{}'::jsonb,
    scene_name              text not null,
    scene_start_date        date,
    scene_end_date          date,
    scene_participants      jsonb default '[]'::jsonb
);