<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Musicx.Application.Desktop\Musicx.Application.Desktop.csproj" />
      <ProjectReference Include="..\Musicx.Domain\Musicx.Domain.csproj" />
    </ItemGroup>

</Project>
