/*
    Extensions
*/

create extension if not exists pg_trgm;

/*
    Artists
*/

create table public.artists (
    artist_id                   bigint generated by default as identity primary key,
    artist_created_at           timestamp without time zone,
    artist_updated_at           timestamp without time zone,
    artist_artwork_url          text,
    artist_country              text,
    artist_description          text,
    artist_name                 text not null,
    artist_region               text,
    artist_town                 text,
    artist_discriminator        varchar(8) not null,
    artist_formation_date       timestamp without time zone,
    artist_split_date           timestamp without time zone,
    artist_first_name           text,
    artist_last_name            text,
    artist_birth_date           timestamp without time zone,
    artist_death_date           timestamp without time zone
);

alter table public.artists owner to postgres;

create index ix_artists_trgm on public.artists using GIN (artist_name gin_trgm_ops);

/*
    Labels
*/

create table public.labels (
    label_id                    bigint generated by default as identity primary key,
    label_created_at            timestamp without time zone,
    label_updated_at            timestamp without time zone,
    label_description           text,
    label_name                  text not null
);

alter table public.labels owner to postgres;

create index ix_labels_trgm on public.labels using GIN (label_name gin_trgm_ops);

/*
    Albums
*/

create table public.albums (
    album_id                        bigint generated by default as identity primary key,
    album_created_at                timestamp without time zone,
    album_updated_at                timestamp without time zone,
    album_artist_id                 bigint references public.artists,
    album_artwork_url               text,
    album_begin_record_date         timestamp without time zone,
    album_disc_total                integer,
    album_end_record_date           timestamp without time zone,
    album_is_far_right              boolean not null,
    album_language                  text,
    album_name                      text not null,
    album_original_release_date     timestamp without time zone,
    album_release_type              integer,
    album_simplified_genre_color    text,
    album_simplified_genre_name     text,
    album_track_total               integer
);

alter table public.albums owner to postgres;

create index ix_albums_artist_id on public.albums (album_artist_id);
create index ix_albums_trgm on public.albums using GIN (album_name gin_trgm_ops);

/*
    BandArtist <=> PersonArtist
*/

create table public.bandartist_personartist (
    bandartist_personartist_band_id   bigint not null references public.artists,
    bandartist_personartist_person_id bigint not null references public.artists,
    primary key (bandartist_personartist_band_id, bandartist_personartist_person_id)
);

alter table public.bandartist_personartist owner to postgres;

create index ix_bandartistpersonartist_person_id on public.bandartist_personartist (bandartist_personartist_person_id);

/*
    Releases
*/

create table public.releases (
    release_id                  bigint generated by default as identity primary key,
    release_created_at          timestamp without time zone,
    release_updated_at          timestamp without time zone,
    release_album_id            bigint references public.albums,
    release_label_id            bigint references public.labels,
    release_catalog_number      text not null,
    release_release_date        timestamp without time zone
);

alter table public.releases owner to postgres;

create index ix_releases_album_id on public.releases (release_album_id);
create index ix_releases_label_id on public.releases (release_label_id);

/*
    Songs
*/

create table public.songs (
    song_id                     bigint generated by default as identity primary key,
    song_created_at             timestamp without time zone,
    song_updated_at             timestamp without time zone,
    song_album_id               bigint references public.albums,
    song_artist_id              bigint references public.artists,
    song_disc_number            integer,
    song_duration               bigint,
    song_lyrics                 text,
    song_title                  text not null,
    song_track_number           integer,
    song_type                   integer,
    song_bit_rate               integer,
    song_file_path              text,
    song_format                 integer,
    song_sample_rate            double precision,
    song_volume_modifier        double precision
);

alter table public.songs owner to postgres;

create index ix_songs_album_id on public.songs (song_album_id);
create index ix_songs_artist_id on public.songs (song_artist_id);
create index ix_songs_trgm on public.songs using GIN (song_title gin_trgm_ops);

/*
    Genres
*/

create table public.genres (
    genre_id                    bigint generated by default as identity primary key,
    genre_created_at            timestamp without time zone,
    genre_updated_at            timestamp without time zone,
    genre_color                 text not null,
    genre_name                  text not null,
    genre_type                  integer not null default 0,
    genre_description           text,
);

alter table public.genres owner to postgres;

create index ix_genres_trgm on public.genres using GIN (genre_name gin_trgm_ops);

/*
    ChildrenGenre <=> ParentGenre
*/

create table public.childrengenre_parentgenre (
    childrengenre_parentgenre_child_id bigint not null references public.genres,
    childrengenre_parentgenre_parent_id   bigint not null references public.genres,
    primary key (childrengenre_parentgenre_child_id, childrengenre_parentgenre_parent_id)
);

alter table public.childrengenre_parentgenre owner to postgres;

create index ix_childrengenreparentgenre_parent_id on public.childrengenre_parentgenre (childrengenre_parentgenre_parent_id);

/*
    Song <=> Genre (Primary)
*/

create table public.song_genre (
    song_genre_song_id          bigint not null references public.songs,
    song_genre_genre_id         bigint not null references public.genres
);

alter table public.song_genre owner to postgres;

create index ix_songgenre_song_id on public.song_genre (song_genre_song_id);

/*
    Song <=> Genre (Influence)
*/

create table public.song_influence (
    song_influence_song_id      bigint not null references public.songs,
    song_influence_genre_id     bigint not null references public.genres
);

alter table public.song_influence owner to postgres;

create index ix_songinfluence_song_id on public.song_influence (song_influence_song_id);

/*
    Album <=> Genre (Primary)
*/

create table public.album_genre (
    album_genre_album_id        bigint not null references public.albums,
    album_genre_genre_id        bigint not null references public.genres
);

alter table public.album_genre owner to postgres;

create index ix_albumgenre_album_id on public.album_genre (album_genre_album_id);

/*
    Album <=> Genre (Influence)
*/

create table public.album_influence (
    album_influence_album_id    bigint not null references public.albums,
    album_influence_genre_id    bigint not null references public.genres
);

alter table public.album_influence owner to postgres;

create index ix_albuminfluence_album_id on public.album_influence (album_influence_album_id);