create table public."Artists"
(
    "Id"            bigint generated by default as identity
        constraint "PK_Artists"
            primary key,
    "CreatedAt"     timestamp without time zone,
    "UpdatedAt"     timestamp without time zone,
    "ArtworkUrl"    text,
    "Country"       text,
    "Name"          text       not null,
    "Discriminator" varchar(8) not null,
    "FormationDate" timestamp without time zone,
    "SplitDate"     timestamp without time zone,
    "FirstName"     text,
    "LastName"      text,
    "BirthDate"     timestamp without time zone,
    "DeathDate"     timestamp without time zone
);

alter table public."Artists"
    owner to postgres;

create table public."Labels"
(
    "Id"          bigint generated by default as identity
        constraint "PK_Labels"
            primary key,
    "CreatedAt"   timestamp without time zone,
    "UpdatedAt"   timestamp without time zone,
    "Description" text,
    "Name"        text not null
);

alter table public."Labels"
    owner to postgres;

create table public."Albums"
(
    "Id"          bigint generated by default as identity
        constraint "PK_Albums"
            primary key,
    "CreatedAt"   timestamp without time zone,
    "UpdatedAt"   timestamp without time zone,
    "ArtistId"    bigint
        constraint "FK_Albums_Artists_ArtistId"
            references public."Artists",
    "ArtworkUrl"  text,
    "DiscTotal"   integer,
    "Name"        text not null,
    "ReleaseDate" timestamp without time zone,
    "ReleaseType" integer,
    "TrackTotal"  integer
);

alter table public."Albums"
    owner to postgres;

create index "IX_Albums_ArtistId"
    on public."Albums" ("ArtistId");

create table public."BandArtist_PersonArtist"
(
    "BandId"   bigint not null
        constraint "FK_BandArtistPersonArtist_Artists_BandsId"
            references public."Artists",
    "PersonId" bigint not null
        constraint "FK_BandArtistPersonArtist_Artists_MembersId"
            references public."Artists",
    constraint "PK_BandArtistPersonArtist"
        primary key ("BandId", "PersonId")
);

alter table public."BandArtist_PersonArtist"
    owner to postgres;

create index "IX_BandArtistPersonArtist_PersonId"
    on public."BandArtist_PersonArtist" ("PersonId");

create table public."Releases"
(
    "Id"            bigint generated by default as identity
        constraint "PK_Releases"
            primary key,
    "CreatedAt"     timestamp without time zone,
    "UpdatedAt"     timestamp without time zone,
    "AlbumId"       bigint
        constraint "FK_Releases_Albums_AlbumId"
            references public."Albums",
    "LabelId"       bigint
        constraint "FK_Releases_Labels_LabelId"
            references public."Labels",
    "CatalogNumber" text not null,
    "ReleaseDate"   timestamp without time zone
);

alter table public."Releases"
    owner to postgres;

create index "IX_Releases_AlbumId"
    on public."Releases" ("AlbumId");

create index "IX_Releases_LabelId"
    on public."Releases" ("LabelId");

create table public."Songs"
(
    "Id"             bigint generated by default as identity
        constraint "PK_Songs"
            primary key,
    "CreatedAt"      timestamp without time zone,
    "UpdatedAt"      timestamp without time zone,
    "AlbumId"        bigint
        constraint "FK_Songs_Albums_AlbumId"
            references public."Albums",
    "ArtistId"       bigint
        constraint "FK_Songs_Artists_ArtistId"
            references public."Artists",
    "DiscNumber"     integer,
    "Duration"       bigint,
    "Lyrics"         text,
    "Title"          text not null,
    "TrackNumber"    integer,
    "BitRate"        integer,
    "FilePath"       text,
    "Format"         integer,
    "SampleRate"     double precision,
    "VolumeModifier" double precision
);

alter table public."Songs"
    owner to postgres;

create index "IX_Songs_AlbumId"
    on public."Songs" ("AlbumId");

create index "IX_Songs_ArtistId"
    on public."Songs" ("ArtistId");

create table public."Genres"
(
    "Id"            bigint generated by default as identity
        constraint "PK_Genres"
            primary key,
    "CreatedAt"     timestamp without time zone,
    "UpdatedAt"     timestamp without time zone,
    "Name"          text not null
);

alter table public."Genres"
    owner to postgres;

create table public."ChildrenGenre_ParentGenre"
(
    "ChildrenId" bigint not null
        constraint "FK_ChildrenGenreParentGenre_Genres_ChildrenId"
            references public."Genres",
    "ParentId"  bigint not null
        constraint "FK_ChildrenGenreParentGenre_Genres_ParentId"
            references public."Genres",
    constraint "PK_GenreGenre"
        primary key ("ChildrenId", "ParentId")
);

alter table public."ChildrenGenre_ParentGenre"
    owner to postgres;

create index "IX_ChildrenGenreParentGenre_ParentId"
    on public."ChildrenGenre_ParentGenre" ("ParentId");

create table public."Song_Genre"
(
    "SongId"    bigint not null
        constraint "FK_SongGenre_Songs_SongId"
            references public."Songs",
    "Level"     integer not null,
    "GenreId"   bigint not null
        constraint "FK_SongGenre_Genres_GenreId"
            references public."Genres"
);

alter table public."Song_Genre"
    owner to postgres;

create index "IX_SongGenre_SongId"
    on public."Song_Genre" ("SongId");

create table public."Album_Genre"
(
    "AlbumId"    bigint not null
        constraint "FK_AlbumGenre_Albums_AlbumId"
            references public."Albums",
    "Level"     integer not null,
    "GenreId"   bigint not null
        constraint "FK_AlbumGenre_Genres_GenreId"
            references public."Genres"
);

alter table public."Album_Genre"
    owner to postgres;

create index "IX_AlbumGenre_AlbumId"
    on public."Album_Genre" ("AlbumId");