INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (1, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (2, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (3, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (4, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (5, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (6, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (7, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (8, 1);
INSERT INTO public.user_role (user_role_user_id, user_role_role_id) VALUES (9, 1);
