//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musicx.Infrastructure.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Musicx.Infrastructure.Shared.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Web_AdminPageCard_Administration {
            get {
                return ResourceManager.GetString("Web.AdminPageCard.Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year(s).
        /// </summary>
        internal static string Web_AlbumTimelineView_Years {
            get {
                return ResourceManager.GetString("Web.AlbumTimelineView.Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years / Graduation.
        /// </summary>
        internal static string Web_AlbumTimelineView_YearsGraduation {
            get {
                return ResourceManager.GetString("Web.AlbumTimelineView.YearsGraduation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-compute final rating when all factors are filled.
        /// </summary>
        internal static string Web_AlbumView_AutoComputeRating {
            get {
                return ResourceManager.GetString("Web.AlbumView.AutoComputeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-calc.
        /// </summary>
        internal static string Web_AlbumView_AutoComputeShort {
            get {
                return ResourceManager.GetString("Web.AlbumView.AutoComputeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string Web_AlbumView_Collection {
            get {
                return ResourceManager.GetString("Web.AlbumView.Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Web_AlbumView_ComputeNow {
            get {
                return ResourceManager.GetString("Web.AlbumView.ComputeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Date.
        /// </summary>
        internal static string Web_AlbumView_DiscoveryDate {
            get {
                return ResourceManager.GetString("Web.AlbumView.DiscoveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album info.
        /// </summary>
        internal static string Web_AlbumView_EditAlbum {
            get {
                return ResourceManager.GetString("Web.AlbumView.EditAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album track info.
        /// </summary>
        internal static string Web_AlbumView_EditTracklist {
            get {
                return ResourceManager.GetString("Web.AlbumView.EditTracklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Rating.
        /// </summary>
        internal static string Web_AlbumView_FanRatingLabel {
            get {
                return ResourceManager.GetString("Web.AlbumView.FanRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed.
        /// </summary>
        internal static string Web_AlbumView_GenreDetailed {
            get {
                return ResourceManager.GetString("Web.AlbumView.GenreDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string Web_AlbumView_GenreSimple {
            get {
                return ResourceManager.GetString("Web.AlbumView.GenreSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string Web_AlbumView_GenresLabel {
            get {
                return ResourceManager.GetString("Web.AlbumView.GenresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Web_AlbumView_GlobalRatingLabel {
            get {
                return ResourceManager.GetString("Web.AlbumView.GlobalRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Web_AlbumView_Label {
            get {
                return ResourceManager.GetString("Web.AlbumView.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Fan Rating.
        /// </summary>
        internal static string Web_AlbumView_NonFanRatingLabel {
            get {
                return ResourceManager.GetString("Web.AlbumView.NonFanRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ratings.
        /// </summary>
        internal static string Web_AlbumView_RatingsSuffix {
            get {
                return ResourceManager.GetString("Web.AlbumView.RatingsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded.
        /// </summary>
        internal static string Web_AlbumView_Recorded {
            get {
                return ResourceManager.GetString("Web.AlbumView.Recorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded {0} → {1}.
        /// </summary>
        internal static string Web_AlbumView_RecordedRange {
            get {
                return ResourceManager.GetString("Web.AlbumView.RecordedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        internal static string Web_AlbumView_ReleasedOn {
            get {
                return ResourceManager.GetString("Web.AlbumView.ReleasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}.
        /// </summary>
        internal static string Web_AlbumView_ReleaseTypeValue {
            get {
                return ResourceManager.GetString("Web.AlbumView.ReleaseTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See on Wikipedia.
        /// </summary>
        internal static string Web_AlbumView_SeeOnWikipedia {
            get {
                return ResourceManager.GetString("Web.AlbumView.SeeOnWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Web_AlbumView_Settings {
            get {
                return ResourceManager.GetString("Web.AlbumView.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide rating factors.
        /// </summary>
        internal static string Web_AlbumView_ToggleAdvancedFactors {
            get {
                return ResourceManager.GetString("Web.AlbumView.ToggleAdvancedFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote genres.
        /// </summary>
        internal static string Web_AlbumView_VoteGenres {
            get {
                return ResourceManager.GetString("Web.AlbumView.VoteGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a review.
        /// </summary>
        internal static string Web_AlbumView_WriteReview {
            get {
                return ResourceManager.GetString("Web.AlbumView.WriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal rating.
        /// </summary>
        internal static string Web_AlbumView_YourRatingHint {
            get {
                return ResourceManager.GetString("Web.AlbumView.YourRatingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        internal static string Web_AlbumViewToolbar_DisplayMode {
            get {
                return ResourceManager.GetString("Web.AlbumViewToolbar.DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Rating.
        /// </summary>
        internal static string Web_AlbumViewToolbar_GlobalRating {
            get {
                return ResourceManager.GetString("Web.AlbumViewToolbar.GlobalRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb. Ratings.
        /// </summary>
        internal static string Web_AlbumViewToolbar_NbRatings {
            get {
                return ResourceManager.GetString("Web.AlbumViewToolbar.NbRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Rating.
        /// </summary>
        internal static string Web_AlbumViewToolbar_PersonalRating {
            get {
                return ResourceManager.GetString("Web.AlbumViewToolbar.PersonalRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string Web_AlbumViewToolbar_ReleaseDate {
            get {
                return ResourceManager.GetString("Web.AlbumViewToolbar.ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Name.
        /// </summary>
        internal static string Web_AlbumViewToolbar_ReleaseName {
            get {
                return ResourceManager.GetString("Web.AlbumViewToolbar.ReleaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search releases....
        /// </summary>
        internal static string Web_AlbumViewToolbar_SearchReleases {
            get {
                return ResourceManager.GetString("Web.AlbumViewToolbar.SearchReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See on Wikipedia.
        /// </summary>
        internal static string Web_ArtistView_SeeOnWikipedia {
            get {
                return ResourceManager.GetString("Web.ArtistView.SeeOnWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Web_Common_Cancel {
            get {
                return ResourceManager.GetString("Web.Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Web_Common_Delete {
            get {
                return ResourceManager.GetString("Web.Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Web_Common_Download {
            get {
                return ResourceManager.GetString("Web.Common.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Web_Common_Follow {
            get {
                return ResourceManager.GetString("Web.Common.Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string Web_Common_List {
            get {
                return ResourceManager.GetString("Web.Common.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ratings.
        /// </summary>
        internal static string Web_Common_Ratings {
            get {
                return ResourceManager.GetString("Web.Common.Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Web_Common_Search {
            get {
                return ResourceManager.GetString("Web.Common.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Web_Common_Sort {
            get {
                return ResourceManager.GetString("Web.Common.Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Web_Common_Warning {
            get {
                return ResourceManager.GetString("Web.Common.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎶 Discover new artists.
        /// </summary>
        internal static string Web_Home_DiscoverArtists {
            get {
                return ResourceManager.GetString("Web.Home.DiscoverArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💿 Explore trending albums.
        /// </summary>
        internal static string Web_Home_ExploreAlbums {
            get {
                return ResourceManager.GetString("Web.Home.ExploreAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest releases.
        /// </summary>
        internal static string Web_Home_LatestReleases {
            get {
                return ResourceManager.GetString("Web.Home.LatestReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} artists, {1} albums, {2} songs &amp; {3} genres.
        /// </summary>
        internal static string Web_Home_Stats {
            get {
                return ResourceManager.GetString("Web.Home.Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎧 Dive into unique genres.
        /// </summary>
        internal static string Web_Home_UniqueGenres {
            get {
                return ResourceManager.GetString("Web.Home.UniqueGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string Web_Home_Welcome {
            get {
                return ResourceManager.GetString("Web.Home.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string Web_Nav_Charts {
            get {
                return ResourceManager.GetString("Web.Nav.Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string Web_Nav_Genres {
            get {
                return ResourceManager.GetString("Web.Nav.Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Web_Nav_Language {
            get {
                return ResourceManager.GetString("Web.Nav.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch notes.
        /// </summary>
        internal static string Web_Nav_PatchNotes {
            get {
                return ResourceManager.GetString("Web.Nav.PatchNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating mode.
        /// </summary>
        internal static string Web_Nav_RatingMode {
            get {
                return ResourceManager.GetString("Web.Nav.RatingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search anything (artist, album, song, genre, user...).
        /// </summary>
        internal static string Web_Nav_SearchLabel {
            get {
                return ResourceManager.GetString("Web.Nav.SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ratings.
        /// </summary>
        internal static string Web_Nav_ShowRatings {
            get {
                return ResourceManager.GetString("Web.Nav.ShowRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Web_Nav_SignIn {
            get {
                return ResourceManager.GetString("Web.Nav.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Web_Nav_SignOut {
            get {
                return ResourceManager.GetString("Web.Nav.SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Web_Nav_Signup {
            get {
                return ResourceManager.GetString("Web.Nav.Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Web_Nav_Version {
            get {
                return ResourceManager.GetString("Web.Nav.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string Web_Search_CreateNew {
            get {
                return ResourceManager.GetString("Web.Search.CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something to display results....
        /// </summary>
        internal static string Web_Search_EmptyHint {
            get {
                return ResourceManager.GetString("Web.Search.EmptyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Web_Search_Loading {
            get {
                return ResourceManager.GetString("Web.Search.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artist found for this query. Do you want to create one?.
        /// </summary>
        internal static string Web_Search_NoArtistFoundPrompt {
            get {
                return ResourceManager.GetString("Web.Search.NoArtistFoundPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search anything....
        /// </summary>
        internal static string Web_Search_Placeholder {
            get {
                return ResourceManager.GetString("Web.Search.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted..
        /// </summary>
        internal static string Web_UserEditor_AccountDeleted {
            get {
                return ResourceManager.GetString("Web.UserEditor.AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-compute advanced ratings.
        /// </summary>
        internal static string Web_UserEditor_AutoComputeAdvancedRatings {
            get {
                return ResourceManager.GetString("Web.UserEditor.AutoComputeAdvancedRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-follow artists with a good rating.
        /// </summary>
        internal static string Web_UserEditor_AutoFollow {
            get {
                return ResourceManager.GetString("Web.UserEditor.AutoFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, rating an album above {0} automatically follows its artist..
        /// </summary>
        internal static string Web_UserEditor_AutoFollowHint {
            get {
                return ResourceManager.GetString("Web.UserEditor.AutoFollowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        internal static string Web_UserEditor_Bio {
            get {
                return ResourceManager.GetString("Web.UserEditor.Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string Web_UserEditor_BirthDate {
            get {
                return ResourceManager.GetString("Web.UserEditor.BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit birth date.
        /// </summary>
        internal static string Web_UserEditor_BirthDateLocked {
            get {
                return ResourceManager.GetString("Web.UserEditor.BirthDateLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string Web_UserEditor_Category_connections {
            get {
                return ResourceManager.GetString("Web.UserEditor.Category.connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Web_UserEditor_Category_display {
            get {
                return ResourceManager.GetString("Web.UserEditor.Category.display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Web_UserEditor_Category_language {
            get {
                return ResourceManager.GetString("Web.UserEditor.Category.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string Web_UserEditor_Category_ratings {
            get {
                return ResourceManager.GetString("Web.UserEditor.Category.ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Web_UserEditor_ChangePassword {
            get {
                return ResourceManager.GetString("Web.UserEditor.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Web_UserEditor_ConfirmPassword {
            get {
                return ResourceManager.GetString("Web.UserEditor.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Google.
        /// </summary>
        internal static string Web_UserEditor_ConnectGoogle {
            get {
                return ResourceManager.GetString("Web.UserEditor.ConnectGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string Web_UserEditor_Connections {
            get {
                return ResourceManager.GetString("Web.UserEditor.Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect LastFM.
        /// </summary>
        internal static string Web_UserEditor_ConnectLastFm {
            get {
                return ResourceManager.GetString("Web.UserEditor.ConnectLastFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin.
        /// </summary>
        internal static string Web_UserEditor_CountryOrigin {
            get {
                return ResourceManager.GetString("Web.UserEditor.CountryOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search country....
        /// </summary>
        internal static string Web_UserEditor_CountrySearchPlaceholder {
            get {
                return ResourceManager.GetString("Web.UserEditor.CountrySearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created on {0}.
        /// </summary>
        internal static string Web_UserEditor_CreatedAt {
            get {
                return ResourceManager.GetString("Web.UserEditor.CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string Web_UserEditor_DarkMode {
            get {
                return ResourceManager.GetString("Web.UserEditor.DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string Web_UserEditor_DeleteAccount {
            get {
                return ResourceManager.GetString("Web.UserEditor.DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting your account cannot be undone. Do you really want to continue?.
        /// </summary>
        internal static string Web_UserEditor_DeleteWarning {
            get {
                return ResourceManager.GetString("Web.UserEditor.DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Web_UserEditor_Display {
            get {
                return ResourceManager.GetString("Web.UserEditor.Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Web_UserEditor_Email {
            get {
                return ResourceManager.GetString("Web.UserEditor.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is null, cannot edit profile..
        /// </summary>
        internal static string Web_UserEditor_Errors_NoUser {
            get {
                return ResourceManager.GetString("Web.UserEditor.Errors.NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password are not the same!.
        /// </summary>
        internal static string Web_UserEditor_Errors_PasswordMismatch {
            get {
                return ResourceManager.GetString("Web.UserEditor.Errors.PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High graphics (animations).
        /// </summary>
        internal static string Web_UserEditor_HighGraphics {
            get {
                return ResourceManager.GetString("Web.UserEditor.HighGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this for a lighter UI without animations/transitions..
        /// </summary>
        internal static string Web_UserEditor_HighGraphicsHint {
            get {
                return ResourceManager.GetString("Web.UserEditor.HighGraphicsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Web_UserEditor_Language {
            get {
                return ResourceManager.GetString("Web.UserEditor.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Web_UserEditor_NewPassword {
            get {
                return ResourceManager.GetString("Web.UserEditor.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password has been saved..
        /// </summary>
        internal static string Web_UserEditor_PasswordSaved {
            get {
                return ResourceManager.GetString("Web.UserEditor.PasswordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred language.
        /// </summary>
        internal static string Web_UserEditor_PreferredLanguage {
            get {
                return ResourceManager.GetString("Web.UserEditor.PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Display Mode.
        /// </summary>
        internal static string Web_UserEditor_RatingMode {
            get {
                return ResourceManager.GetString("Web.UserEditor.RatingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string Web_UserEditor_Ratings {
            get {
                return ResourceManager.GetString("Web.UserEditor.Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        internal static string Web_UserEditor_SavePassword {
            get {
                return ResourceManager.GetString("Web.UserEditor.SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        internal static string Web_UserEditor_SaveProfile {
            get {
                return ResourceManager.GetString("Web.UserEditor.SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string Web_UserEditor_SaveSettings {
            get {
                return ResourceManager.GetString("Web.UserEditor.SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ratings.
        /// </summary>
        internal static string Web_UserEditor_ShowRatings {
            get {
                return ResourceManager.GetString("Web.UserEditor.ShowRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to edit your profile..
        /// </summary>
        internal static string Web_UserEditor_SignInRequired {
            get {
                return ResourceManager.GetString("Web.UserEditor.SignInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Web_UserEditor_SignOut {
            get {
                return ResourceManager.GetString("Web.UserEditor.SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Album Genre Display.
        /// </summary>
        internal static string Web_UserEditor_SimpleGenreDisplay {
            get {
                return ResourceManager.GetString("Web.UserEditor.SimpleGenreDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Web_UserEditor_TabProfile {
            get {
                return ResourceManager.GetString("Web.UserEditor.TabProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Web_UserEditor_TabSettings {
            get {
                return ResourceManager.GetString("Web.UserEditor.TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string Web_UserEditor_Title {
            get {
                return ResourceManager.GetString("Web.UserEditor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload avatar.
        /// </summary>
        internal static string Web_UserEditor_UploadAvatar {
            get {
                return ResourceManager.GetString("Web.UserEditor.UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Web_UserEditor_Username {
            get {
                return ResourceManager.GetString("Web.UserEditor.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been saved..
        /// </summary>
        internal static string Web_UserEditor_UserSaved {
            get {
                return ResourceManager.GetString("Web.UserEditor.UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years old.
        /// </summary>
        internal static string Web_UserView_AgeYearsOld {
            get {
                return ResourceManager.GetString("Web.UserView.AgeYearsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Web_UserView_Album {
            get {
                return ResourceManager.GetString("Web.UserView.Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} album(s).
        /// </summary>
        internal static string Web_UserView_AlbumsCount {
            get {
                return ResourceManager.GetString("Web.UserView.AlbumsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A–M artists ratio.
        /// </summary>
        internal static string Web_UserView_ArtistsRatioAM {
            get {
                return ResourceManager.GetString("Web.UserView.ArtistsRatioAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average rating.
        /// </summary>
        internal static string Web_UserView_AverageRating {
            get {
                return ResourceManager.GetString("Web.UserView.AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear ratings.
        /// </summary>
        internal static string Web_UserView_ClearRatings {
            get {
                return ResourceManager.GetString("Web.UserView.ClearRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string Web_UserView_Collection {
            get {
                return ResourceManager.GetString("Web.UserView.Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Web_UserView_Date {
            get {
                return ResourceManager.GetString("Web.UserView.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all ratings cannot be undone. Are you sure you want to continue?.
        /// </summary>
        internal static string Web_UserView_DeleteRatingsWarning {
            get {
                return ResourceManager.GetString("Web.UserView.DeleteRatingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string Web_UserView_EditProfile {
            get {
                return ResourceManager.GetString("Web.UserView.EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export ratings.
        /// </summary>
        internal static string Web_UserView_ExportRatings {
            get {
                return ResourceManager.GetString("Web.UserView.ExportRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite albums.
        /// </summary>
        internal static string Web_UserView_FavouriteAlbums {
            get {
                return ResourceManager.GetString("Web.UserView.FavouriteAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite genres.
        /// </summary>
        internal static string Web_UserView_FavouriteGenres {
            get {
                return ResourceManager.GetString("Web.UserView.FavouriteGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Web_UserView_Friends {
            get {
                return ResourceManager.GetString("Web.UserView.Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined {0} ago.
        /// </summary>
        internal static string Web_UserView_JoinedAgo {
            get {
                return ResourceManager.GetString("Web.UserView.JoinedAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most rated release year.
        /// </summary>
        internal static string Web_UserView_MostRatedReleaseYear {
            get {
                return ResourceManager.GetString("Web.UserView.MostRatedReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No genre data available..
        /// </summary>
        internal static string Web_UserView_NoGenreData {
            get {
                return ResourceManager.GetString("Web.UserView.NoGenreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ratings to export..
        /// </summary>
        internal static string Web_UserView_NoRatingsToExport {
            get {
                return ResourceManager.GetString("Web.UserView.NoRatingsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin.
        /// </summary>
        internal static string Web_UserView_OriginCountry {
            get {
                return ResourceManager.GetString("Web.UserView.OriginCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Web_UserView_Rating {
            get {
                return ResourceManager.GetString("Web.UserView.Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating distribution.
        /// </summary>
        internal static string Web_UserView_RatingDistribution {
            get {
                return ResourceManager.GetString("Web.UserView.RatingDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string Web_UserView_Ratings {
            get {
                return ResourceManager.GetString("Web.UserView.Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings exported successfully..
        /// </summary>
        internal static string Web_UserView_RatingsExportSuccess {
            get {
                return ResourceManager.GetString("Web.UserView.RatingsExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating standard deviation.
        /// </summary>
        internal static string Web_UserView_RatingStandardDeviation {
            get {
                return ResourceManager.GetString("Web.UserView.RatingStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        internal static string Web_UserView_Raw {
            get {
                return ResourceManager.GetString("Web.UserView.Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ratings....
        /// </summary>
        internal static string Web_UserView_SearchRatings {
            get {
                return ResourceManager.GetString("Web.UserView.SearchRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the format you want to download..
        /// </summary>
        internal static string Web_UserView_SelectExportFormat {
            get {
                return ResourceManager.GetString("Web.UserView.SelectExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Web_UserView_Statistics {
            get {
                return ResourceManager.GetString("Web.UserView.Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found, cannot export ratings..
        /// </summary>
        internal static string Web_UserView_UserNotFoundExport {
            get {
                return ResourceManager.GetString("Web.UserView.UserNotFoundExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted.
        /// </summary>
        internal static string Web_UserView_Weighted {
            get {
                return ResourceManager.GetString("Web.UserView.Weighted", resourceCulture);
            }
        }
    }
}
