/*
    Songs
*/

drop table if exists public.songs cascade;

create table public.songs (
    song_id                     bigint generated by default as identity primary key,
    song_created_at             timestamp without time zone,
    song_updated_at             timestamp without time zone,
    song_album_id               bigint references public.albums,
    song_artist_id              bigint references public.artists,
    song_disc_number            integer,
    song_duration               bigint,
    song_lyrics                 text,
    song_title                  text not null,
    song_track_number           integer,
    song_type                   integer not null default 0
);

alter table public.songs owner to postgres;

create index ix_songs_album_id on public.songs (song_album_id);
create index ix_songs_artist_id on public.songs (song_artist_id);
create index ix_songs_trgm on public.songs using GIN (song_title gin_trgm_ops);

\i 'Songs/CreateSongRatingStatTable.sql'
\i 'Songs/CreateSongAudioDataTable.sql'

\i 'Songs/CreateSongGenreTable.sql'
\i 'Songs/CreateSongInfluenceTable.sql'