/*
    Extensions
*/

create extension if not exists pg_trgm;
create extension if not exists citext;

/*
    Artists
*/

create table public.artists (
    artist_id                   bigint generated by default as identity primary key,
    artist_created_at           timestamp without time zone,
    artist_updated_at           timestamp without time zone,
    artist_artwork_url          text,
    artist_country              text,
    artist_description          text,
    artist_name                 text not null,
    artist_region               text,
    artist_town                 text,
    artist_discriminator        varchar(8) not null,
    artist_formation_date       timestamp without time zone,
    artist_split_date           timestamp without time zone,
    artist_first_name           text,
    artist_last_name            text,
    artist_birth_date           timestamp without time zone,
    artist_death_date           timestamp without time zone
);

alter table public.artists owner to postgres;

create index ix_artists_trgm on public.artists using GIN (artist_name gin_trgm_ops);

/*
    Labels
*/

create table public.labels (
    label_id                    bigint generated by default as identity primary key,
    label_created_at            timestamp without time zone,
    label_updated_at            timestamp without time zone,
    label_description           text,
    label_name                  text not null
);

alter table public.labels owner to postgres;

create index ix_labels_trgm on public.labels using GIN (label_name gin_trgm_ops);

/*
    Albums
*/

create table public.albums (
    album_id                        bigint generated by default as identity primary key,
    album_created_at                timestamp without time zone,
    album_updated_at                timestamp without time zone,
    album_artist_id                 bigint references public.artists,
    album_artwork_url               text,
    album_begin_record_date         timestamp without time zone,
    album_disc_total                integer,
    album_end_record_date           timestamp without time zone,
    album_is_far_right              boolean not null,
    album_language                  text,
    album_name                      text not null,
    album_original_release_date     timestamp without time zone,
    album_release_type              integer,
    album_simplified_genre_color    text,
    album_simplified_genre_name     text,
    album_track_total               integer
);

alter table public.albums owner to postgres;

create index ix_albums_artist_id on public.albums (album_artist_id);
create index ix_albums_trgm on public.albums using GIN (album_name gin_trgm_ops);

/*
    BandArtist <=> PersonArtist
*/

create table public.bandartist_personartist (
    bandartist_personartist_band_id   bigint not null references public.artists,
    bandartist_personartist_person_id bigint not null references public.artists,
    primary key (bandartist_personartist_band_id, bandartist_personartist_person_id)
);

alter table public.bandartist_personartist owner to postgres;

create index ix_bandartistpersonartist_person_id on public.bandartist_personartist (bandartist_personartist_person_id);

/*
    Releases
*/

create table public.releases (
    release_id                  bigint generated by default as identity primary key,
    release_created_at          timestamp without time zone,
    release_updated_at          timestamp without time zone,
    release_album_id            bigint references public.albums,
    release_label_id            bigint references public.labels,
    release_catalog_number      text not null,
    release_release_date        timestamp without time zone
);

alter table public.releases owner to postgres;

create index ix_releases_album_id on public.releases (release_album_id);
create index ix_releases_label_id on public.releases (release_label_id);

/*
    Songs
*/

create table public.songs (
    song_id                     bigint generated by default as identity primary key,
    song_created_at             timestamp without time zone,
    song_updated_at             timestamp without time zone,
    song_album_id               bigint references public.albums,
    song_artist_id              bigint references public.artists,
    song_disc_number            integer,
    song_duration               bigint,
    song_lyrics                 text,
    song_title                  text not null,
    song_track_number           integer,
    song_type                   integer,
    song_bit_rate               integer,
    song_file_path              text,
    song_format                 integer,
    song_sample_rate            double precision,
    song_volume_modifier        double precision
);

alter table public.songs owner to postgres;

create index ix_songs_album_id on public.songs (song_album_id);
create index ix_songs_artist_id on public.songs (song_artist_id);
create index ix_songs_trgm on public.songs using GIN (song_title gin_trgm_ops);

/*
    Genres
*/

create table public.genres (
    genre_id                    bigint generated by default as identity primary key,
    genre_created_at            timestamp without time zone,
    genre_updated_at            timestamp without time zone,
    genre_color                 text not null,
    genre_name                  text not null,
    genre_type                  integer not null default 0,
    genre_description           text
);

alter table public.genres owner to postgres;

create index ix_genres_trgm on public.genres using GIN (genre_name gin_trgm_ops);

/*
    ChildrenGenre <=> ParentGenre
*/

create table public.childrengenre_parentgenre (
    childrengenre_parentgenre_child_id bigint not null references public.genres,
    childrengenre_parentgenre_parent_id   bigint not null references public.genres,
    primary key (childrengenre_parentgenre_child_id, childrengenre_parentgenre_parent_id)
);

alter table public.childrengenre_parentgenre owner to postgres;

create index ix_childrengenreparentgenre_parent_id on public.childrengenre_parentgenre (childrengenre_parentgenre_parent_id);

/*
    Song <=> Genre (Primary)
*/

create table public.song_genre (
    song_genre_song_id          bigint not null references public.songs,
    song_genre_genre_id         bigint not null references public.genres,
    primary key (song_genre_song_id, song_genre_genre_id)
);

alter table public.song_genre owner to postgres;

create index ix_songgenre_song_id on public.song_genre (song_genre_song_id);

/*
    Song <=> Genre (Influence)
*/

create table public.song_influence (
    song_influence_song_id      bigint not null references public.songs,
    song_influence_genre_id     bigint not null references public.genres,
    primary key (song_influence_song_id, song_influence_genre_id)
);

alter table public.song_influence owner to postgres;

create index ix_songinfluence_song_id on public.song_influence (song_influence_song_id);

/*
    Album <=> Genre (Primary)
*/

create table public.album_genre (
    album_genre_album_id        bigint not null references public.albums,
    album_genre_genre_id        bigint not null references public.genres,
    primary key (album_genre_album_id, album_genre_genre_id)
);

alter table public.album_genre owner to postgres;

create index ix_albumgenre_album_id on public.album_genre (album_genre_album_id);

/*
    Album <=> Genre (Influence)
*/

create table public.album_influence (
    album_influence_album_id    bigint not null references public.albums,
    album_influence_genre_id    bigint not null references public.genres,
    primary key (album_influence_album_id, album_influence_genre_id)
);

alter table public.album_influence owner to postgres;

create index ix_albuminfluence_album_id on public.album_influence (album_influence_album_id);

/*
    Users
*/

create table public.users (
    user_id                     bigint generated by default as identity primary key,
    user_created_at             timestamp without time zone,
    user_updated_at             timestamp without time zone,
    user_email                  varchar(320) not null unique,
    user_email_confirmed        boolean not null,
    user_name                   varchar(50) not null unique CHECK (char_length(user_name) >= 3),
    user_password_hash          text,
    user_password_salt          text,
    user_google_id              text,
    user_lastfm_username        text
);

alter table public.users owner to postgres;

create unique index ix_users_email_lower on public.users (lower(user_email));
create index ix_users_trgm on public.users using GIN (user_name gin_trgm_ops);

/*
    Roles 
*/
    
create table public.roles(
    role_id                     smallint generated by default as identity primary key,
    role_created_at             timestamp without time zone,
    role_updated_at             timestamp without time zone,
    role_name                   varchar(50) not null unique
);

/*
    User <=> Role 
*/

create table public.user_roles (
    user_id bigint not null references public.users(user_id) on delete cascade,
    role_id smallint not null references public.roles(role_id) on delete cascade,
    primary key (user_id, role_id)
);

/*
    Permissions
*/
    
create table public.permissions (
    permission_id               smallint generated by default as identity primary key,
    permission_created_at       timestamp without time zone,
    permission_updated_at       timestamp without time zone,
    permission_name             varchar(100) not null unique
);

/*
    Role <=> Permissions
*/

create table public.role_permission (
    role_permission_role_id         smallint not null references public.roles(role_id) on delete cascade,
    role_permission_permission_id   bigint not null references public.permissions(permission_id) on delete cascade,
    primary key (role_permission_role_id, role_permission_permission_id)
);

/*
    Tags
*/

create table public.tags (
    tag_id                      bigint generated by default as identity primary key,
    tag_created_at              timestamp without time zone,
    tag_updated_at              timestamp without time zone,
    tag_name                    citext not null unique,
    tag_slug                    text generated always as (
        regexp_replace(lower(tag_name), '\s+', '-', 'g')
    ) STORED
);

create index ix_tags_trgm on public.tags using GIN (tag_name gin_trgm_ops);

/*
    Artist <= Ratings => User
*/

create table public.user_artist_ratings(
    user_artist_ratings_user_id                     bigint references public.users(user_id) on delete cascade,
    user_artist_ratings_artist_id                   bigint references public.artists(artist_id) on delete cascade,
    user_artist_ratings_created_at                  timestamp without time zone,
    user_artist_ratings_updated_at                  timestamp without time zone,
    user_artist_ratings_rating                      smallint not null check (user_artist_ratings_rating between 0 and 100),
    primary key (user_artist_ratings_user_id, user_artist_ratings_artist_id)
);

create index ix_uar_artist on public.user_artist_ratings (user_artist_ratings_artist_id, user_artist_ratings_rating);
create index ix_uar_user on public.user_artist_ratings (user_artist_ratings_user_id);

/*
    Artist <= Tags => User
*/

create table public.user_artist_tags (
    user_artist_tags_user_id                     bigint references public.users(user_id) on delete cascade,
    user_artist_tags_artist_id                   bigint references public.artists(artist_id) on delete cascade,
    user_artist_tags_tag_id                      bigint references public.tags(tag_id) on delete cascade,
    user_artist_tags_created_at                  timestamp without time zone,
    primary key (user_artist_tags_user_id, user_artist_tags_artist_id, user_artist_tags_tag_id)
);

create index ix_uat_tag_artist on public.user_artist_tags (user_artist_tags_tag_id, user_artist_tags_artist_id);
create index ix_uat_artist_tag on public.user_artist_tags (user_artist_tags_artist_id, user_artist_tags_tag_id);
create index ix_uat_user_tag   on public.user_artist_tags (user_artist_tags_user_id, user_artist_tags_tag_id);

/*
    Album <= Attrs => User
*/

create table public.user_album_attrs (
    user_album_attrs_user_id                     bigint references public.users(user_id) on delete cascade,
    user_album_attrs_album_id                    bigint references public.albums(album_id) on delete cascade,
    user_album_attrs_created_at                  timestamp without time zone,
    user_album_attrs_updated_at                  timestamp without time zone,
    user_album_attrs_rating                      smallint check (user_album_attrs_rating between 0 and 100),
    user_album_attrs_collection_type             integer not null,
    user_album_attrs_review                      text,
    primary key (user_album_attrs_user_id, user_album_attrs_album_id)
);

create index ix_uaa_album on public.user_album_attrs (user_album_attrs_album_id);
create index ix_uaa_user on public.user_album_attrs (user_album_attrs_user_id);
create index ix_uaa_album_rating on public.user_album_attrs (user_album_attrs_album_id, user_album_attrs_rating) where user_album_attrs_rating is not null;

/*
    Album <= Tags => User
*/

create table public.user_album_tags (
    user_album_tags_user_id                     bigint references public.users(user_id) on delete cascade,
    user_album_tags_album_id                    bigint references public.albums(album_id) on delete cascade,
    user_album_tags_tag_id                      bigint references public.tags(tag_id) on delete cascade,
    user_album_tags_created_at                  timestamp without time zone,
    primary key (user_album_tags_user_id, user_album_tags_album_id, user_album_tags_tag_id)
);

create index ix_uatg_tag_album on public.user_album_tags (user_album_tags_tag_id, user_album_tags_album_id);
create index ix_uatg_album_tag on public.user_album_tags (user_album_tags_album_id, user_album_tags_tag_id);
create index ix_uatg_user_tag  on public.user_album_tags (user_album_tags_user_id, user_album_tags_tag_id);

/*
    Song <= Ratings => User 
*/

create table public.user_song_ratings (
    user_song_ratings_user_id                   bigint references public.users(user_id) on delete cascade,
    user_song_ratings_song_id                   bigint references public.songs(song_id) on delete cascade,
    user_song_ratings_created_at                timestamp without time zone,
    user_song_ratings_updated_at                timestamp without time zone,
    user_song_ratings_rating                    smallint not null check (user_song_ratings_rating between 0 and 100),
    primary key (user_song_ratings_user_id, user_song_ratings_song_id)
);

create index ix_usr_song on public.user_song_ratings (user_song_ratings_song_id, user_song_ratings_rating);
create index ix_usr_user on public.user_song_ratings (user_song_ratings_user_id);

/*
    Song <= Tags => User 
*/

create table public.user_song_tags (
    user_song_tags_user_id                  bigint references public.users(user_id) on delete cascade,
    user_song_tags_song_id                  bigint references public.songs(song_id) on delete cascade,
    user_song_tags_tag_id                   bigint references public.tags(tag_id) on delete cascade,
    user_song_tags_created_at               timestamp without time zone,
    primary key (user_song_tags_user_id, user_song_tags_song_id, user_song_tags_tag_id)
);

create index ix_ust_tag_song on public.user_song_tags (user_song_tags_tag_id, user_song_tags_song_id);
create index ix_ust_song_tag on public.user_song_tags (user_song_tags_song_id, user_song_tags_tag_id);
create index ix_ust_user_tag on public.user_song_tags (user_song_tags_user_id, user_song_tags_tag_id);

/*
    Artists Ranking Stats 
*/

create table public.artist_rating_stats (
    artist_rating_stats_artist_id           bigint primary key references public.artists(artist_id) on delete cascade,
    artist_rating_stats_count               integer not null default 0,
    artist_rating_stats_sum                 integer not null default 0,
    artist_rating_stats_avg                 numeric(5,2) not null default 0
);

/*
    Artists Ranking Stats 
*/

create table public.album_rating_stats (
    album_rating_stats_album_id             bigint primary key references public.albums(album_id) on delete cascade,
    album_rating_stats_count                integer not null default 0,
    album_rating_stats_sum                  integer not null default 0,
    album_rating_stats_avg                  numeric(5,2) not null default 0
);

/*
    Artists Ranking Stats 
*/

create table public.song_rating_stats (
    song_rating_stats_song_id               bigint primary key references public.songs(song_id) on delete cascade,
    song_rating_stats_count                 integer not null default 0,
    song_rating_stats_sum                   integer not null default 0,
    song_rating_stats_avg                   numeric(5,2) not null default 0
);