<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
      <PackageReference Include="log4net" Version="3.0.4" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
      <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
      <PackageReference Include="WPF-UI" Version="4.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\Images\Logo\" />
      <Folder Include="Modals\" />
      <Folder Include="Pages\Encyclopedia\" />
      <Folder Include="Pages\Friends\" />
      <Folder Include="Pages\ListenTogether\" />
      <Folder Include="Pages\OnlineStreaming\" />
      <Folder Include="Pages\Profile\" />
      <Folder Include="Pages\Settings\ViewModels\" />
      <Folder Include="Pages\Settings\Views\" />
      <Folder Include="Pages\Statistics\" />
      <Folder Include="UIComponents\TopBar\ViewModels\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Images\Logo\logo500.png" />
      <Resource Include="Assets\Images\Logo\Logo500.png" />
      <None Remove="Assets\Fonts\SpaceGrotesk-VariableFont_wght.ttf" />
      <Resource Include="Assets\Fonts\SpaceGrotesk-VariableFont_wght.ttf" />
      <None Update="log4net.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Page Update="Main\Views\MainWindowView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UIComponents\AudioPlayer\Views\AudioPlayerView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UIComponents\AppInfoBar\Views\AppInfoBar.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UIComponents\TopBar\Views\TopBar.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Pages\PageSelector\Views\PageSelectorView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Pages\LocalLibrary\Views\LocalLibraryView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Musicx.Core\Musicx.Core.csproj" />
        <ProjectReference Include="..\Musicx.Infrastructure\Musicx.Infrastructure.csproj" />
    </ItemGroup>

</Project>
