<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Musicx.Application.Shared\Musicx.Application.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Interfaces\UseCases\Artist\" />
      <Folder Include="Interfaces\UseCases\Event\" />
      <Folder Include="Interfaces\UseCases\Genre\" />
      <Folder Include="Interfaces\UseCases\Labell\" />
      <Folder Include="Interfaces\UseCases\Tag\" />
    </ItemGroup>

</Project>
