<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Musicx.Application.Shared\Musicx.Application.Shared.csproj" />
      <ProjectReference Include="..\Musicx.Domain\Musicx.Domain.csproj" />
    </ItemGroup>

</Project>
