<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Api\Persistence\Repositories\" />
      <Folder Include="API\Persistence\Schema\_Fixtures\" />
      <Folder Include="Desktop\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Musicx.Application.Api\Musicx.Application.Api.csproj" />
      <ProjectReference Include="..\Musicx.Application.Shared\Musicx.Application.Shared.csproj" />
      <ProjectReference Include="..\Musicx.Application.Desktop\Musicx.Application.Desktop.csproj" />
      <ProjectReference Include="..\Musicx.Application.Web\Musicx.Application.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="log4net" Version="3.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
      <PackageReference Include="z440.atl.core" Version="6.22.0" />
    </ItemGroup>

</Project>
