<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Musicx.Core\Musicx.Core.csproj" />
        <ProjectReference Include="..\Musicx.Data\Musicx.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="log4net" Version="3.0.4" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
        <PackageReference Include="NAudio" Version="2.2.1" />
        <PackageReference Include="NAudio.Asio" Version="2.2.1" />
        <PackageReference Include="NAudio.Flac" Version="1.0.5702.29018" />
        <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
        <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
        <PackageReference Include="TagLibSharp" Version="2.3.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

</Project>
