/*
    Band Member Period
*/

drop table if exists public.band_member_period cascade;

create table public.band_member_period (
    band_member_period_id bigint generated by default as identity primary key,
    
    band_member_period_band_id bigint not null,
    band_member_period_member_id bigint not null,
    
    band_member_period_from_year smallint,
    band_member_period_to_year smallint,

    constraint fk_band_member
        foreign key (band_member_period_band_id, band_member_period_member_id)
            references public.band_member (band_member_band_id, band_member_member_id),
    
    constraint chk_year_order
        check (
            band_member_period_from_year is null
            or band_member_period_to_year is null
            or band_member_period_from_year <= band_member_period_to_year
        )
);

alter table public.band_member_period owner to postgres;