/*
    Artists
*/

drop table if exists public.artists cascade;

create table public.artists (
    artist_id                           bigint generated by default as identity primary key,
    artist_created_at                   timestamp without time zone,
    artist_updated_at                   timestamp without time zone,
    artist_alias                        text,
    artist_artwork_url                  text,
    artist_calculated_genres            text,
    artist_calculated_influences        text,
    artist_calculated_genre_counts      text,
    artist_calculated_influence_counts  text,
    artist_calculated_descriptor_counts text,
    artist_calculated_scene_counts      text,
    artist_calculated_movement_counts   text,
    artist_current_country              text,
    artist_current_region               text,
    artist_current_town                 text,
    artist_description                  text,
    artist_is_visible                   bool not null default false,
    artist_name                         text not null,
    artist_origin_country               text,
    artist_origin_region                text,
    artist_origin_town                  text,
    artist_wikipedia_url                text,
    
    artist_discriminator                varchar(8) not null,
    
    artist_formation_date               timestamp without time zone,
    artist_split_date                   timestamp without time zone,
    artist_first_name                   text,
    artist_last_name                    text,
    artist_birth_date                   timestamp without time zone,
    artist_death_date                   timestamp without time zone
);

alter table public.artists owner to postgres;

create index ix_artists_trgm on public.artists using GIN (artist_name gin_trgm_ops);

\i 'Artists/CreateArtistRatingStatTable.sql'

\i 'Artists/CreateBandMemberTable.sql'