/*
    Facets
*/

drop table if exists public.facets cascade;

create table public.facets (
    facet_id                            bigint generated by default as identity primary key,
    facet_created_at                    timestamp without time zone,
    facet_updated_at                    timestamp without time zone,
    facet_name                          text not null unique,
    facet_type                          text not null,
    facet_description                   text
);

alter table public.facets owner to postgres;

\i 'Facets/CreateGenreFacetTable.sql'