/*
    Review Sources
*/

drop table if exists public.review_source_users cascade;
drop table if exists public.review_sources cascade;

create table public.review_sources (
    review_source_id                              bigint generated by default as identity primary key,
    review_source_name                            varchar(120) not null unique,
    review_source_url                             text not null,
    review_source_color                           varchar(16) not null
);

alter table public.review_sources owner to postgres;

create table public.review_source_users (
    review_source_users_review_source_id          bigint not null references public.review_sources(review_source_id) on delete cascade,
    review_source_users_user_id                   bigint not null references public.users(user_id) on delete cascade,
    primary key (review_source_users_review_source_id, review_source_users_user_id)
);

alter table public.review_source_users owner to postgres;
create index ix_review_source_users_user on public.review_source_users(review_source_users_user_id);