/*
    Albums
*/

drop table if exists public.albums cascade;

create table public.albums (
    album_id                        bigint generated by default as identity primary key,
    album_created_at                timestamp without time zone,
    album_updated_at                timestamp without time zone,
    album_artist_id                 bigint references public.artists,
    album_artist_alias              text,
    album_artwork_url               text,
    album_begin_record_date         timestamp without time zone,
    album_disc_total                integer,
    album_end_record_date           timestamp without time zone,
    album_english_name              text,
    album_is_explicit_content       bool not null default false,
    album_is_far_right              bool not null default false,
    album_is_graphic_content        bool not null default false,
    album_is_visible                bool not null default false,
    album_language                  text,
    album_name                      text not null,
    album_original_release_date     timestamp without time zone,
    album_release_type              integer,
    album_simplified_genre_color    text,
    album_simplified_genre_name     text,
    album_total_duration            bigint,
    album_track_total               integer,
    album_wikipedia_url             text
);

alter table public.albums owner to postgres;

create index ix_albums_artist_id on public.albums (album_artist_id);
create index ix_albums_trgm on public.albums using GIN (album_name gin_trgm_ops);

\i 'Albums/CreateAlbumRatingStatTable.sql'

\i 'Albums/CreateAlbumGenreTable.sql'
\i 'Albums/CreateAlbumInfluenceTable.sql'