<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Interfaces\UseCases\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Musicx.Application.Common\Musicx.Application.Common.csproj" />
      <ProjectReference Include="..\Musicx.Domain\Musicx.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
    </ItemGroup>

</Project>
