<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)GeneratedRazor</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="8.2.4" />
        <PackageReference Include="ISO3166-updated" Version="1.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.3"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />
        <PackageReference Include="MudBlazor" Version="8.12.0" />
        <PackageReference Include="MudBlazor.ThemeManager" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Musicx.Application.Shared\Musicx.Application.Shared.csproj" />
      <ProjectReference Include="..\..\Musicx.Contracts\Musicx.Contracts.csproj" />
      <ProjectReference Include="..\..\Musicx.Infrastructure\Musicx.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="appsettings.Client.json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Components\Artists\" />
      <Folder Include="Modals\Admin\Songs\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Auth\AuthorizeView.razor" />
      <_ContentIncludedByDefault Remove="Components\Fields\CstDurationField.razor" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Layout\Auth\AuthorizeView.razor" />
    </ItemGroup>

</Project>
