/*
    Tags
*/

drop table if exists public.tags cascade;

create table public.tags (
    tag_id                      bigint generated by default as identity primary key,
    tag_created_at              timestamp without time zone,
    tag_updated_at              timestamp without time zone,
    tag_name                    citext not null unique,
    tag_slug                    text generated always as (
        regexp_replace(lower(tag_name), '\s+', '-', 'g')
    ) STORED
);

alter table public.tags owner to postgres;

create index ix_tags_trgm on public.tags using GIN (tag_name gin_trgm_ops);