/*
    Permissions
*/

drop table if exists public.permissions cascade;

create table public.permissions (
    permission_id               smallint generated by default as identity primary key,
    permission_created_at       timestamp without time zone,
    permission_updated_at       timestamp without time zone,
    permission_name             varchar(100) not null unique
);

alter table public.permissions owner to postgres;