<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="log4net" Version="3.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.7" />
      <PackageReference Include="NAudio" Version="2.2.1" />
      <PackageReference Include="NAudio.Asio" Version="2.2.1" />
      <PackageReference Include="NAudio.Flac" Version="1.0.5702.29018" />
      <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
      <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="TagLibSharp" Version="2.3.0" />
      <PackageReference Include="WPF-UI" Version="4.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\Images\Logo\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Images\Logo\logo500.png" />
      <Resource Include="Assets\Images\Logo\Logo500.png" />
      <None Remove="Assets\Fonts\SpaceGrotesk-VariableFont_wght.ttf" />
      <Resource Include="Assets\Fonts\SpaceGrotesk-VariableFont_wght.ttf" />
      <None Update="log4net.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\Navigation\AppInfoBar.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MusicxApi\MusicxApi.csproj" />
    </ItemGroup>

</Project>
