/*
    Users
*/

drop table if exists public.users cascade;

create table public.users (
    user_id                     bigint generated by default as identity primary key,
    user_created_at             timestamp without time zone,
    user_updated_at             timestamp without time zone,
    user_email                  varchar(320) not null unique,
    user_email_confirmed        boolean not null,
    user_name                   varchar(50) not null unique CHECK (char_length(user_name) >= 3),
    user_password_hash          text,
    user_password_salt          text,
    user_google_id              text,
    user_lastfm_username        text
);

alter table public.users owner to postgres;

create unique index ix_users_email_lower on public.users (lower(user_email));
create index ix_users_trgm on public.users using GIN (user_name gin_trgm_ops);

\i 'Users/CreateUserRoleTable.sql'

\i 'Users/CreateUserArtistRatingTable.sql'
\i 'Users/CreateUserArtistTagTable.sql'

\i 'Users/CreateUserAlbumAttributeTable.sql'
\i 'Users/CreateUserAlbumTagTable.sql'

\i 'Users/CreateUserSongRatingTable.sql'
\i 'Users/CreateUserSongTagTable.sql'