/*
    Releases
*/

drop table if exists public.releases cascade;

create table public.releases (
    release_id                  bigint generated by default as identity primary key,
    release_created_at          timestamp without time zone,
    release_updated_at          timestamp without time zone,
    release_album_id            bigint references public.albums,
    release_label_id            bigint references public.labels,
    release_catalog_number      text not null,
    release_is_visible          bool not null default false,
    release_release_date        timestamp without time zone
);

alter table public.releases owner to postgres;

create index ix_releases_album_id on public.releases (release_album_id);
create index ix_releases_label_id on public.releases (release_label_id);