/*
    Roles 
*/

drop table if exists public.roles cascade;

create table public.roles(
    role_id                     smallint generated by default as identity primary key,
    role_created_at             timestamp without time zone,
    role_updated_at             timestamp without time zone,
    role_name                   varchar(50) not null unique
);

alter table public.roles owner to postgres;

\i 'Roles/CreateRolePermissionTable.sql'